### ISSUE TITLE
Replace cosmos related suggestion into help with kvd ones

### ISSUE THREAD

**Issue by gbunea** [Kava-Labs/kava#102]
Please see attached files: 
<img width="1053" alt="Screenshot 2019-06-30 at 23 11 52" src="https://user-images.githubusercontent.com/15690364/60401855-fc7a1a80-9b8f-11e9-849e-5bd9d2a40d26.png">

**Comment by iammelea** [comment]
seems like some gaiacli missing in the text have o be replaced.

```
kvcli tx slashing unjail -h
unjail a jailed validator:

$ gaiacli tx slashing unjail --from mykey
```

**Comment by karzak** [comment]
Fixed upstream in Gaia. Debug output should use `kvcli` now.
