### ISSUE TITLE
tcp 127.0.0.1:26657 connection refused

### ISSUE THREAD

**Issue by aliqasemzadeh** [Kava-Labs/kava#1025]
Hi
I get error:
````
ERROR: Status: Post failed: Post "http://localhost:26657": dial tcp 127.0.0.1:26657: connect: connection refused
````

**Comment by dualsystems** [comment]
please provide:  ss -anpolt or netstat -anpol

**Comment by pirtleshell** [comment]
hello, it appears you don't have a node running locally. you can point your cli at a live node via the `--node` flag, ex: `--node https://rpc.kava.io:443`
please let us know if any problems persist and we can reopen this ticket.
