### ISSUE TITLE
Deprecated command - buf protoc

### ISSUE THREAD

**Issue by mfridman** [Kava-Labs/kava#1160]
Hey there, interesting project.

Just a heads up the `buf protoc` command has moved to `buf alpha protoc` and may in the future be deprecated entirely. More details here: https://github.com/bufbuild/buf/pull/915

I noticed it was being used here: https://github.com/Kava-Labs/kava/blob/master/scripts/protocgen.sh#L20

Bonus, it'd be pretty neat if you published the protos to the Buf Schema Registry. Happy to help if you have any questions.

**Comment by cipherzzz** [comment]
happy to help if you want to assign to me - this is a year old, though @mfridman

**Comment by mfridman** [comment]
I don't think this is relevant anymore, seems like this project uses both `buf` and `protoc`.

Going to close this.
