### ISSUE TITLE
0kava is smaller than 2500kava: insufficient funds: insufficient funds

### ISSUE THREAD

**Issue by nanyounanyounan** [Kava-Labs/kava#1195]
0kava is smaller than 2500kava: insufficient funds: insufficient funds
![image](https://user-images.githubusercontent.com/32302366/159897119-8e52a97e-f097-43ea-8fb4-839f08765f0a.png)
Transfer 0.1 failed
why?

**Comment by pirtleshell** [comment]
hello, support for these kinds of requests is best received through discord. i hope you were able to resolve your problem. if not, could you please proved more details as to what kind of tx you were posting?
please provide any commands or interfaces used, a tx hash if available, and an account address.
