### ISSUE TITLE
Node Sync not stopping

### ISSUE THREAD

**Issue by ratneshpatil-rp** [Kava-Labs/kava#1390]
We are using ubuntu 20.0.4 VM. Some how we not able to stop the node sync.
What is command to stop node sync.

**Comment by ratneshpatil-rp** [comment]
@nddeluca can you please check this its urgent we are running out of space

**Comment by nddeluca** [comment]
Hi @ratneshpatil-rp, you can stop the process to stop syncing -- there isn't a way to pause it, a node will always attempt to sync to the tip of the chain.

There are also pruning settings you can set in the `.kava/config/app.toml`, you can set `pruning = "everything"` in that file to start pruning the application state
