### ISSUE TITLE
Add support for the Ledger Nano S Plus

### ISSUE THREAD

**Issue by colossus-digital** [Kava-Labs/kava#1418]
Add support for the Ledger Nano S Plus, please (The Nano S is no longer available for purchase)

```
lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 004: ID 2c97:5011 Ledger Nano S Plus <-------------------------
Bus 002 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub

./kava-v0.19.0-linux-amd64 keys add test --coin-type 118 --ledger
Error: failed to generate ledger key: failed to retrieve device: ledger nano S: no ledger connected
```

**Comment by pirtleshell** [comment]
ledger support is handled via the cosmos-sdk so any problems or feature requests should be reported to that repo. that said, i believe the nano s is supported. please ensure the cosmos app is open on your ledger.

closing for now but feel free to respond if the problem persists and i can reopen.
