### ISSUE TITLE
Kava Transactions

### ISSUE THREAD

**Issue by ratneshpatil-rp** [Kava-Labs/kava#1500]
Hi Team,

@nddeluca Could help with this?
so for the following api-
https://api.data.kava.io/txs?message.sender=kava1qd9vw4dm9rj5jr4ee9qaq585l78cc38z56grww&page=1&limit=100
gives all transactions sent from the address.

Is there any api that returns list of transactions received by a particular address.
also on Swagger we can see that 
https://api.data.kava.io/txs?message.action=send&message.sender=kava1qd9vw4dm9rj5jr4ee9qaq585l78cc38z56grww&page=1&limit=100
this is supporting but we are not getting any txns for it.

Can you also send any api where this message.action works.

**Comment by ratneshpatil-rp** [comment]
Hi @nddeluca ,

for address kava10gwh3w2eyzk3lc70x8jq5nxmq5u4f5hwy99p5r

explorer mintscan shows there are 3 delegate and 3 receive type.
https://api.data.kava.io/txs?message.sender=kava10gwh3w2eyzk3lc70x8jq5nxmq5u4f5hwy99p5r&page=1&limit=100
we are getting only delegate transactions.
Is there any api to fetch the receive transaction type.

Also is there any api to fetch for each transaction type separately.

Thank you

**Comment by karzak** [comment]
@ratneshpatil-rp does https://api.data.kava.io/txs?transfer.recipient=kava10gwh3w2eyzk3lc70x8jq5nxmq5u4f5hwy99p5r&page=1&limit=100 work?

**Comment by ratneshpatil-rp** [comment]
Yes @karzak 
Works! Thank You!

Last Question,
Also is there any api to fetch for each transaction type separately.
For example I want to fetch only the redelegate transaction for a particular address

**Comment by karzak** [comment]
https://api.data.kava.io/txs?message.action=/cosmos.staking.v1beta1.MsgBeginRedelegate&message.sender= kava10gwh3w2eyzk3lc70x8jq5nxmq5u4f5hwy99p5r&page=1&limit=100 should work - I don't think that account has made any redelegations, so the result is empty. @ratneshpatil-rp

**Comment by ratneshpatil-rp** [comment]
How are able to figure out message.action for each transaction type is ther any documentation?
can you provide how we get that for each transaction type

**Comment by karzak** [comment]
https://github.com/Kava-Labs/kava/blob/master/docs/core/proto-docs.md gives the proto defs for kava defined messages and https://github.com/cosmos/cosmos-sdk/blob/v0.45.14/docs/core/proto-docs.md has them for cosmos-sdk

**Comment by ratneshpatil-rp** [comment]
Yes Works!
Awesome Thanks for the help @karzak  and @nddeluca !
Really appreciate the efforts!
