### ISSUE TITLE
kava can not start after upgrade

### ISSUE THREAD

**Issue by zhangsj** [Kava-Labs/kava#1592]
panic: UnmarshalJSON cannot decode empty bytes
May 18 03:10:04 kava kava[74909]: goroutine 1 [running]:
May 18 03:10:04 kava kava[74909]: github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x37be6b0, 0xc0013b83d0}, 0xc000c1d3d0, {0x378b930, 0xc00bb7fa20}, {0x378b980, 0xc00bb7fb90}, {0xc00bfb42e8, 0x7, 0x18}, ...}, ...)

**Comment by nddeluca** [comment]
We haven't seen any other occurrences with this error.  Are you starting v0.23.0 from a v0.21.x that has reached the upgrade block?

**Comment by zhangsj** [comment]
yes.Using a snapshot can not sync also

**Comment by pirtleshell** [comment]
hello @zhangsj, you will receive better support for these issues on discord.

what do you mean by "can not sync"? does it produce any error messages? what pruning settings and database are you running your node with? please provide information on what resources your machine has, what snapshot you tried using and what binary version of kava you are running.

**Comment by pirtleshell** [comment]
closing this. please reopen if you continue to have problems syncing your node.

**Comment by msmania** [comment]
I think I hit the same issue.  This happens when we run a newer client on an old snapshot.  For example, the current archival snapshot at https://quicksync.io/networks/kava.html was created on 2023-04-25.  The latest version 0.24 could not load this snapshot and I needed to downgrade the client to v0.21.
