### ISSUE TITLE
panic: validator set is empty after InitGenesis

### ISSUE THREAD

**Issue by jadechip** [Kava-Labs/kava#1600]
Hi We are working on supporting Kava in our Kubernetes infrastructure. 
I was able to get a node up and running and synced in our dev cluster, but when I copied the underlying disk and restored it in our staging environment I get the following error:
```panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({824634060256})```
I tried deleting the config directory and regenerating it using kava init $HOSTNAME --chain-id $KAVACLIARG_CHAIN_ID --overwrite but to no avail.
Any ideas what the problem could be? 
Cross-posting here as well as Discord as our upcoming deadline is approaching..

**Comment by pirtleshell** [comment]
hello, `init` only sets up the data and config directories. depending on the network you want to connect to, you must download the genesis separately. however, syncing from scratch can take a very long time. we recommend bootstrapping the node from a snapshot like those available at quicksync or polkachu.

there are details on how to setup a node in our [public docs](https://docs.kava.io/docs/participate/validator-node#configuring-your-node).

[Quicksync snapshots](https://quicksync.io/networks/kava.html)
[Polkachu Snapshots](https://polkachu.com/tendermint_snapshots/kava)

please let us know if you run into any problems.

**Comment by jadechip** [comment]
There appears to to have been a problem with my snapshot. I've created a new snapshot from the original disk and everything works now. Thank you!
