### ISSUE TITLE
Packet forward middleware

### ISSUE THREAD

**Issue by faddat** [Kava-Labs/kava#1633]
Today, Josh Lee asked:

"Does Kava have packet forward middleware?"

And really it seemed like a great idea, so I figured I'd make a PR for that. 

https://twitter.com/dogemos/status/1671807504043618304

## Plan 

* #1634 
* #1635 
* x to n: enable linters one by one
* add PFM

**Comment by pirtleshell** [comment]
thanks for you help and contributions!

PFM was added on the v0.26.0 mainnet upgrade
