### ISSUE TITLE
Kava Node Not Syncing

### ISSUE THREAD

**Issue by ratneshpatil-rp** [Kava-Labs/kava#1644]
Hi Team,

As per Documentation we followed the Steps-

setup a new home: kava --home ~/.kava init my-moniker --chain-id kava_2222-10
remove its data dir & genesis file: rm -fr ~/.kava/data ~/.kava/config/genesis.json
download snapshot: https://quicksync.io/networks/kava.html
download genesis: https://kava-genesis-files.s3.us-east-1.amazonaws.com/kava_2222-10/genesis.json
extract snapshot & put in kava home
move genesis to ~/.kava/config/genesis.json
update persistent_peers in config.toml to what you have in your gist (https://gist.github.com/ratneshpatil-rp/8d04c9e131f4cfd28b813a89917eeae7)(leave seeds blank)
run kava start

We Followed the Steps but still unable to connect to peers-
We are getting error-
10:55AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}} server=node
10:55AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM INF Reconnecting to peer addr={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} module=p2p server=node
10:55AM INF minted coins from module account amount=187debt from=cdp module=x/bank
10:55AM INF minted coins from module account amount=187usdx from=liquidator module=x/bank
10:55AM INF minted coins from module account amount=50debt from=cdp module=x/bank
10:55AM INF minted coins from module account amount=50usdx from=liquidator module=x/bank
10:55AM INF minted coins from module account amount=33683debt from=cdp module=x/bank
10:55AM INF minted coins from module account amount=33683usdx from=liquidator module=x/bank
10:55AM INF burned tokens from module account amount=70950debt from=liquidator module=x/bank
10:55AM INF burned tokens from module account amount=70950usdx from=liquidator module=x/bank
10:55AM INF service start impl="Peer{MConn{94.130.78.22:26656} 2a15d9c39eea97b4cf00480b45d4ea32a2e173d0 out}" module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM INF service start impl=MConn{94.130.78.22:26656} module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM INF Connection is closed @ recvRoutine (likely by the other side) conn={"Logger":{}} module=p2p peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM INF service stop impl={"Logger":{}} module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}} server=node
10:55AM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} server=node
10:55AM INF Reconnecting to peer addr={"id":"2a15d9c39eea97b4cf00480b45d4ea32a2e173d0","ip":"94.130.78.22","port":26656} module=p2p server=node
goroutine 175 [running]:
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x37e4690, 0xc0013600f0}, 0xc000128b18, {0x37b1910, 0xc001733a70}, {0x37b1960, 0xc001733be0}, {0xc001ce3e60, 0x7, 0x18}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/params/types/subspace.go:110 +0x2c7
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.MinCommissionRate(...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/keeper/params.go:53
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.GetParams({{0x37b1910, 0xc001733a30}, {0x37e4690, 0xc0013600f0}, {0x37d63a0, 0xc001139680}, {0x7f9862f75ab0, 0xc000bdfb80}, {0x37e41f8, 0xc000de46f0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/keeper/params.go:65 +0x5c8
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.ApplyAndReturnValidatorSetUpdates({{0x37b1910, 0xc001733a30}, {0x37e4690, 0xc0013600f0}, {0x37d63a0, 0xc001139680}, {0x7f9862f75ab0, 0xc000bdfb80}, {0x37e41f8, 0xc000de46f0}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/keeper/val_state_change.go:109 +0xbb
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.BlockValidatorUpdates({{0x37b1910, 0xc001733a30}, {0x37e4690, 0xc0013600f0}, {0x37d63a0, 0xc001139680}, {0x7f9862f75ab0, 0xc000bdfb80}, {0x37e41f8, 0xc000de46f0}, ...}, ...)

can you let us know what should we do now?
on friday we had started the container, how much time it will require

**Comment by ratneshpatil-rp** [comment]
Hi Team,

https://dl2.quicksync.io/kava_2222-10-default.20230425.0110.tar.lz4

Can we confirm is this Archieval snapshot?

**Comment by ratneshpatil-rp** [comment]
Can you share the link to get kava-10_2222, archival snapshot.

**Comment by pirtleshell** [comment]
@ratneshpatil-rp archive files of data directories are available from [quicksync](https://quicksync.io/networks/kava.html) and from [polkachu](https://polkachu.com/tendermint_snapshots/kava).

At the time of writing this comment, the latest pruned node snapshot from quicksync is [here](https://dl2.quicksync.io/kava_2222-10-pruned.20230629.0210.tar.lz4).

I see now that the quicksync default pruning archive has not been updated since april (hence the snapshot you linked!). we'll ping them to see if it can be updated. if you start your node from the pruned snapshot, you should be able to start your node (and it wont be so far behind once actually up and running)

**Comment by icculp** [comment]
@ratneshpatil-rp I had to sync from scratch, took me like 2 months. I do not know if any publicly available archival snapshots

**Comment by ratneshpatil-rp** [comment]
so We were trying Docker method-
1) where clone version- git clone -b v0.24.0 https://github.com/Kava-Labs/kava
2) Build Image- docker build -t
3) with same image we initialised kava- sudo docker run -it  -p 26657:26657 -p 26656:26656  -v /NewDisk23Machine/node-kava/kava/.kava:/kava/.kava kava:Latest kavad init nodekava --chain-id kava_2222-10
4) In Config-> config.toml update Peerslist with https://gist.github.com/ratneshpatil-rp/8d04c9e131f4cfd28b813a89917eeae7
5) downloaded Genesis.json- https://kava-genesis-files.s3.us-east-1.amazonaws.com/kava_2222-10/genesis.json
6) started Kava node- sudo docker run -d -it -p 26657:26657 -p 26656:26656 -v /NewDisk23Machine/node-kava/kava/.kava:/kava/.kava  kava:Latest kava start  --pruning nothing --home /kava/.kava

But Getting Error-
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1381898]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
        math/big/int.go:41
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)

**Comment by icculp** [comment]
@ratneshpatil-rp https://docs.kava.io/docs/participate/faq/historic-data/

You need to start at 0 and then upgrade at the corresponding height to the proper version to continue along to the next version. You can use cosmovisor or do it manually

**Comment by ratneshpatil-rp** [comment]
@icculp  Actually we just wanted data for chainid 10.
This there any steps to set-up node and start node for current chain.

https://docs.kava.io/docs/participate/faq/historic-data/ in this link there is data for alll chain but not continuous sequence of blocks.
like kava 2 end at 2598890
but kava3 at 1552962 which is low!

**Comment by pirtleshell** [comment]
@ratneshpatil-rp please see the note on that linked doc:
> As of the Kava 10 release, all upgrades are done as in-place software upgrades. The chain id no longer updates and the block height is never reset to 0, as was the case with all upgrades prior to Kava 10.

before chain id `kava_2222-10` the chain height was reset after each upgrade. to begin syncing the current chain, follow the instructions [here](https://docs.kava.io/docs/participate/node-setup-guide). the genesis file in those instructions is for block 0 of `kava_2222-10` which includes the net state of all the previous chains.

**Comment by pirtleshell** [comment]
hello @ratneshpatil-rp, i'm happy to inform you that we have renewed out partnership with ChainLayer, and full archive node snapshots are available from Quicksync: https://quicksync.io/networks/kava.html

to run a full archive node, you will want to use the file for network "kava_2222-10-archive". they continue to provide fully pruned snapshots as well ("kava_2222-10-pruned") if you don't need access to the full history of the kava_2222-10 chain.
