### ISSUE TITLE
Kava branch handling big genesis.json

### ISSUE THREAD

**Issue by alpha-omega-labs** [Kava-Labs/kava#1656]
Hello, do you have the fully buildable branch of kava that have this fully incorporated https://github.com/cometbft/cometbft/pull/1017
So not only this wonderful comebft commit but also it within kava
Thank you!

**Comment by drklee3** [comment]
Hello, the cometbft PR has been merged in if you would want to use that now. We are using it in our latest master branch, but unfortunately can't offer any support on forks or external modification
