### ISSUE TITLE
RAM Issue!

### ISSUE THREAD

**Issue by ratneshpatil-rp** [Kava-Labs/kava#1740]
We started Kava Archieval Node on our Virtual Machine which has configuration- Standard E8ads v5 (8 vcpus, 64 GiB memory)

we used db_backend = "rocksdb" started the node-

rocksdb:7.10.2 is the kava rocksdb image

command sudo docker run -d -it -p 26657:26657 -p 26656:26656 -p 1317:1317 -v /NewDisk121Machine/node-kava2/kava/.kava:/kava/.kava rocksdb:7.10.2 kava start --pruning nothing --home /kava/.kava 

but after while the container is stopping consuming all 64gb ram. 
What should be the RAM there so that it doesnt stops?

**Comment by ratneshpatil-rp** [comment]
curl --location --request GET 'http://api.data.kava.io/cosmos/base/tendermint/v1beta1/blocks/latest' \
--header 'accept: application/json'

this gives response but when even run in server with 
curl --location --request GET 'http://localhost:26656/cosmos/base/tendermint/v1beta1/blocks/latest' \
--header 'accept: application/json'  gettu=ing 404 error

**Comment by drklee3** [comment]
Please check if you are using the correct port that is configured in your `app.toml` file, 1317 should be the default api port. 26656 is by default for peer connections.

**Comment by ratneshpatil-rp** [comment]
curl: (7) Failed to connect to localhost port 1317 after 0 ms: Connection refused
Getting this when used curl --location --request GET 'http://localhost:1317/cosmos/base/tendermint/v1beta1/blocks/latest'

**Comment by ratneshpatil-rp** [comment]
@drklee3 any update?

**Comment by drklee3** [comment]
64gb should be sufficient to run a kava node, 128gb to provide more headroom. Initial startup may have used more memory than usual

**Comment by ratneshpatil-rp** [comment]
Thanks alot @drklee3, you guys are amazing!
