### ISSUE TITLE
Run a full node error

### ISSUE THREAD

**Issue by orange723** [Kava-Labs/kava#1763]
https://docs.kava.io/docs/participate/node-setup-guide#creating-a-new-data-folder-using-node-tar-file

1. use https://github.com/Kava-Labs/kava/releases/download/v0.24.1/kava-v0.24.1-linux-amd64
2. ./kava init ubuntu --chain-id kava_2222-10
3. ./kava tendermint unsafe-reset-all --home $HOME/.kava
4. edit ~/.kava/config/config.toml  persistent_peers/seeds
5. use https://kava-genesis-files.s3.us-east-1.amazonaws.com/kava_2222-10/genesis.json
6. ./kava start 

run erros 

-------------------------------------------------------------------------------------------------------------------------
`9:47PM INF service start impl=PubSub module=pubsub msg={} server=node
9:47PM INF service start impl=IndexerService module=txindex msg={} server=node
9:47PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=0.24.1
9:47PM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
9:47PM INF initializing blockchain state from genesis.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11db768]

goroutine 1 [running]:
math/big.(*Int).Sign(...)
        math/big/int.go:49
github.com/cosmos/cosmos-sdk/types.Dec.IsNegative(...)
        github.com/cosmos/cosmos-sdk@v0.46.11/types/decimal.go:211
github.com/cosmos/cosmos-sdk/x/staking/types.validateMinCommissionRate({0x27aace0?, 0x0?})
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/types/params.go:226 +0x48
github.com/cosmos/cosmos-sdk/x/params/types.Subspace.SetParamSet({{_, _}, _, {_, _}, {_, _}, {_, _, _}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/params/types/subspace.go:262 +0x1c4
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.SetParams(...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/keeper/params.go:71
github.com/cosmos/cosmos-sdk/x/staking/keeper.Keeper.InitGenesis({{0x34ae9e8, 0x4001489580}, {0x34e3a80, 0x4000942000}, {0x34d0a48, 0x4001626500}, {0xffff685f64a0, 0x4001595760}, {0x34e1740, 0x400000e510}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/keeper/genesis.go:28 +0x1a4
github.com/cosmos/cosmos-sdk/x/staking.AppModule.InitGenesis({{{0x34eb020, 0x4000942000}}, {{0x34ae9e8, 0x4001489580}, {0x34e3a80, 0x4000942000}, {0x34d0a48, 0x4001626500}, {0xffff685f64a0, 0x4001595760}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/x/staking/module.go:152 +0xb8
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x34ce938, 0x4d488c0}, {0x34e39a0, 0x4000824cc0}, {{0x0, 0x0}, {0x400129a220, 0xc}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/types/module/module.go:322 +0x274
github.com/kava-labs/kava/app.(*App).InitChainer(_, {{0x34ce938, 0x4d488c0}, {0x34e39a0, 0x4000824cc0}, {{0x0, 0x0}, {0x400129a220, 0xc}, 0x0, ...}, ...}, ...)
        github.com/kava-labs/kava/app/app.go:1049 +0x1dc
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x40016ec380, {{0x0, 0xeda205790, 0x0}, {0x400129a220, 0xc}, 0x40007990c0, {0x4000332000, 0x64, 0x64}, ...})
        github.com/cosmos/cosmos-sdk@v0.46.11/baseapp/abci.go:71 +0x30c
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x4000786480, {{0x0, 0xeda205790, 0x0}, {0x400129a220, 0xc}, 0x40007990c0, {0x4000332000, 0x64, 0x64}, ...})
        github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:272 +0x188
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x400117f410?, {{0x0, 0xeda205790, 0x0}, {0x400129a220, 0xc}, 0x40007990c0, {0x4000332000, 0x64, 0x64}, ...})
        github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:77 +0x80
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x27da6a5, 0x7}}, {0x400129a220, 0xc}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:319 +0xb80
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x40011b2f30, {0x34e5ba8, 0x4001696820})
        github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:268 +0x324
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x27da6a5, 0x7}}, {0x400129a220, 0xc}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/node/node.go:329 +0x11c
github.com/tendermint/tendermint/node.NewNode(0x400168e780, {0x34b3860, 0x400169d720}, 0x400035ce20, {0x34a32c0, 0x40001801f8}, 0x34a32a0?, 0x40016b6000?, 0x40011b4168, {0x34ce900, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/node/node.go:779 +0x3ec
github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x34f8b40, 0x4001682990}, 0x0, {0x40005f1380, 0xc}, {0x34eb020, ...}, ...}, ...)
        github.com/evmos/ethermint@v0.21.0/server/start.go:373 +0xbb8
github.com/evmos/ethermint/server.StartCmd.func2(0x4001234400?, {0x4d488c0?, 0x0?, 0x0?})
        github.com/evmos/ethermint@v0.21.0/server/start.go:157 +0x264
github.com/spf13/cobra.(*Command).execute(0x400123ec00, {0x4d488c0, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x400121ac00)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x21e2280?, {0x27d62a5, 0x4}, {0x400129a360, 0xb})
        github.com/cosmos/cosmos-sdk@v0.46.11/server/cmd/execute.go:36 +0x158
main.main()
        github.com/kava-labs/kava/cmd/kava/main.go:16 +0x3c`
-------------------------------------------------------------------------------------------------------------------------

`root@ubuntu:~/go/bin# ./kava start
9:11PM INF Unlocking keyring
9:11PM INF starting ABCI with Tendermint
9:11PM INF starting node with ABCI Tendermint in-process
9:11PM INF service start impl=multiAppConn module=proxy msg={} server=node
9:11PM INF service start connection=query impl=localClient module=abci-client msg={} server=node
9:11PM INF service start connection=snapshot impl=localClient module=abci-client msg={} server=node
9:11PM INF service start connection=mempool impl=localClient module=abci-client msg={} server=node
9:11PM INF service start connection=consensus impl=localClient module=abci-client msg={} server=node
9:11PM INF service start impl=EventBus module=events msg={} server=node
9:11PM INF service start impl=PubSub module=pubsub msg={} server=node
9:11PM INF service start impl=IndexerService module=txindex msg={} server=node
9:11PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=0.24.1
9:11PM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
9:11PM INF initializing blockchain state from genesis.json
9:11PM INF created new capability module=ibc name=ports/transfer
9:11PM INF port binded module=x/ibc/port port=transfer
9:11PM INF claimed capability capability=1 module=transfer name=ports/transfer
9:11PM INF asserting crisis invariants inv=1/23 module=x/crisis name=bank/nonnegative-outstanding
9:11PM INF asserting crisis invariants inv=2/23 module=x/crisis name=bank/total-supply
9:11PM INF asserting crisis invariants inv=3/23 module=x/crisis name=staking/module-accounts
9:11PM INF asserting crisis invariants inv=4/23 module=x/crisis name=staking/nonnegative-power
9:11PM INF asserting crisis invariants inv=5/23 module=x/crisis name=staking/positive-delegation
9:11PM INF asserting crisis invariants inv=6/23 module=x/crisis name=staking/delegator-shares
9:11PM INF asserting crisis invariants inv=7/23 module=x/crisis name=gov/module-account
9:11PM INF asserting crisis invariants inv=8/23 module=x/crisis name=distribution/nonnegative-outstanding
9:11PM INF asserting crisis invariants inv=9/23 module=x/crisis name=distribution/can-withdraw
9:11PM INF asserting crisis invariants inv=10/23 module=x/crisis name=distribution/reference-count
9:11PM INF asserting crisis invariants inv=11/23 module=x/crisis name=distribution/module-account
9:11PM INF asserting crisis invariants inv=12/23 module=x/crisis name=evmutil/fully-backed
9:11PM INF asserting crisis invariants inv=13/23 module=x/crisis name=evmutil/small-balances
9:11PM INF asserting crisis invariants inv=14/23 module=x/crisis name=evmutil/cosmos-coins-fully-backed
9:11PM INF asserting crisis invariants inv=15/23 module=x/crisis name=swap/pool-records
9:11PM INF asserting crisis invariants inv=16/23 module=x/crisis name=swap/share-records
9:11PM INF asserting crisis invariants inv=17/23 module=x/crisis name=swap/pool-reserves
9:11PM INF asserting crisis invariants inv=18/23 module=x/crisis name=swap/pool-shares
9:11PM INF asserting crisis invariants inv=19/23 module=x/crisis name=earn/vault-records
9:11PM INF asserting crisis invariants inv=20/23 module=x/crisis name=earn/share-records
9:11PM INF asserting crisis invariants inv=21/23 module=x/crisis name=earn/vault-shares
9:11PM INF asserting crisis invariants inv=22/23 module=x/crisis name=savings/deposits
9:11PM INF asserting crisis invariants inv=23/23 module=x/crisis name=savings/solvency
9:11PM INF asserted all invariants duration=2.366531 height=0 module=x/crisis
panic: validator set is empty after InitGenesis, please ensure at least one validator is initialized with a delegation greater than or equal to the DefaultPowerReduction ({274886436064})
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x34ce938, 0x4d488c0}, {0x34e39a0, 0x400078a3c0}, {{0x0, 0x0}, {0x40013405f0, 0xc}, 0x0, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.46.11/types/module/module.go:336 +0x33c
github.com/kava-labs/kava/app.(*App).InitChainer(_, {{0x34ce938, 0x4d488c0}, {0x34e39a0, 0x400078a3c0}, {{0x0, 0x0}, {0x40013405f0, 0xc}, 0x0, ...}, ...}, ...)
        github.com/kava-labs/kava/app/app.go:1049 +0x1dc
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0x40009588c0, {{0x394abe3e, 0xedcd1a0bf, 0x0}, {0x40013405f0, 0xc}, 0x4000376ca0, {0x4d488c0, 0x0, 0x0}, ...})
        github.com/cosmos/cosmos-sdk@v0.46.11/baseapp/abci.go:71 +0x30c
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0x40017b5ce0, {{0x394abe3e, 0xedcd1a0bf, 0x0}, {0x40013405f0, 0xc}, 0x4000376ca0, {0x4d488c0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.27/abci/client/local_client.go:272 +0x188
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x40014d1d10?, {{0x394abe3e, 0xedcd1a0bf, 0x0}, {0x40013405f0, 0xc}, 0x4000376ca0, {0x4d488c0, 0x0, 0x0}, ...})
        github.com/tendermint/tendermint@v0.34.27/proxy/app_conn.go:77 +0x80
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x27da6a5, 0x7}}, {0x40013405f0, 0xc}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:319 +0xb80
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0x40008aaf30, {0x34e5ba8, 0x4001834270})
        github.com/tendermint/tendermint@v0.34.27/consensus/replay.go:268 +0x324
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x27da6a5, 0x7}}, {0x40013405f0, 0xc}, 0x1, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/node/node.go:329 +0x11c
github.com/tendermint/tendermint/node.NewNode(0x4000142dc0, {0x34b3860, 0x40012830e0}, 0x4001422120, {0x34a32c0, 0x4000120e40}, 0x34a32a0?, 0x40007de340?, 0x40008ac168, {0x34ce900, ...}, ...)
        github.com/tendermint/tendermint@v0.34.27/node/node.go:779 +0x3ec
github.com/evmos/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x34f8b40, 0x400091d4d0}, 0x0, {0x4001752000, 0x4}, {0x34eb020, ...}, ...}, ...)
        github.com/evmos/ethermint@v0.21.0/server/start.go:373 +0xbb8
github.com/evmos/ethermint/server.StartCmd.func2(0x4001712b00?, {0x4d488c0?, 0x0?, 0x0?})
        github.com/evmos/ethermint@v0.21.0/server/start.go:157 +0x264
github.com/spf13/cobra.(*Command).execute(0x4001719200, {0x4d488c0, 0x0, 0x0})
        github.com/spf13/cobra@v1.6.1/command.go:916 +0x658
github.com/spf13/cobra.(*Command).ExecuteC(0x40016a5200)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.6.1/command.go:961
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x21e2280?, {0x27d62a5, 0x4}, {0x40012ce350, 0xb})
        github.com/cosmos/cosmos-sdk@v0.46.11/server/cmd/execute.go:36 +0x158
main.main()
        github.com/kava-labs/kava/cmd/kava/main.go:16 +0x3c`
-------------------------------------------------------------------------------------------------------------------------

this is kava docs persistent_peers and seeds

`persistent_peers = "2a15d9c39eea97b4cf00480b45d4ea32a2e173d0@94.130.78.22:26656,5a933891627e8bde0c4bd0b43c9f99b706e520a2@141.95.99.214:11656,ab3064c37d406245fa2d6e6109395518e8ac8a4c@95.111.255.148:26656,41d88639239c55fd37279d24df507238e1c417ea@85.237.192.104:26656,b23050c89f8cb2f4099688b2bcd60f49b15f41d1@95.214.53.217:26656,d5db8898d40054c07442f3364b32f7fac2752f5e@188.34.178.92:26656,fc34d9a3aff6026a3dbd531a96a50680df61dd91@50.116.3.21:26656,50e4cad7d5e28f7b6495168f92e12bf810e293fd@142.132.152.187:10856,6885971cdb724fa93034fb9e6a11113a6f555d2a@15.235.53.92:11656,7b5a2b519cb5a7d70f0fc5842829d4cce1262585@65.108.121.153:26656,51cfccb07d5a45efdf98d005159c01f0656751ad@54.165.27.59:26656,f7c894901f450b92614fd051d10854d168ec30b5@65.21.94.20:10856,7393ed21b6dc516fcc0ad33c4fe42bdd295d2795@18.206.217.244:26656,508d7ec33c7f3c9c479ca9b845cadbbefee670f7@162.55.133.237:21656,d68410115d7681196651e7fece9e4cafc0456856@3.0.206.176:26656,4cfdd459466cfd492d66b7a5fe26cde96e35d735@182.48.203.7:26656,63ec88e98fc267fb82fa62a51ca5c0a2c115d749@51.38.53.4:27656,ebc272824924ea1a27ea3183dd0b9ba713494f83@185.16.39.172:26656,4efe3caf3b8c0ca197d40756f3bb1bd6081bf18d@51.210.220.20:36656,c124ce0b508e8b9ed1c5b6957f362225659b5343@136.243.248.185:26656,82588f011491c6100d922d133f52fc23460b9231@95.217.91.233:26656,8b5c4a890c8ae7efbbe3360af71be1c3c3a9e12e@121.78.241.68:46656,ce203135031ab08fc0ddff5bd13806e25f21b91d@3.115.125.121:26656,dcd6026ebe5586ed0e94751090f8290b5997666b@5.189.165.172:26656,bc61c26018f65e54232b7e9e99bf7599dffeb78b@13.56.56.180:26656"
seeds = "b334e291ac361f9a1cf253d290047700b488b679@52.2.147.96:26656"`

What should I do?

**Comment by pirtleshell** [comment]
Hello @orange723, thanks for your interest in running a full node.

You will need to use the correct binary version for each major kava version, starting with v0.17.7. For details on the versions, see https://docs.kava.io/docs/participate/faq/historic-data/

We recommend running kava with [cosmovisor](https://docs.cosmos.network/v0.50/build/tooling/cosmovisor) to manage the binary switching for you.

**Comment by orange723** [comment]
Is there a complete documentation that I can deploy against?
