### ISSUE TITLE
Getting block 0 returns block 1 on ethereum rpc

### ISSUE THREAD

**Issue by ozgrakkurt** [Kava-Labs/kava#1802]
If you make this request:
```json
{
		"id": 1,
		"jsonrpc": "2.0",
		"method": "eth_getBlockByNumber",
		"params": ["0x0", true]
}
```
to https://evm.kava.io

you get `"number": "0x1",` in returned block.

And you get the same response if you send
```json
{
		"id": 1,
		"jsonrpc": "2.0",
		"method": "eth_getBlockByNumber",
		"params": ["0x1", true]
}
```

IMO it should be returning the genesis block when 0x0 is passed and the first block when 0x1 is passed, if they are the same block it should return number field according to the request parameter.

**Comment by pirtleshell** [comment]
Hello @ozgrakkurt ,

Blocks start at height 1. Block 0 does not exist so will have undefined behavior when requested. The existing behavior is inherited from go-ethereum.

**Comment by ozgrakkurt** [comment]
> Hello @ozgrakkurt ,
> 
> 
> 
> Blocks start at height 1. Block 0 does not exist so will have undefined behavior when requested. The existing behavior is inherited from go-ethereum.

Hello,

Afaik It is not how go ethereum works with ethereum. If you query with same params you get 0 block and the first block and the returned object has 0 and 1 as block number. This is how most rpcs work like polygon eth, bsc etc.

If 0 block doesn't exist rpc could return the first block but put 0 in the block number field?

**Comment by ozgrakkurt** [comment]
Hey @pirtleshell could you take another look?

**Comment by pirtleshell** [comment]
Hi,

Unfortunately we don't plan to look into this. Block zero does not exist so requesting it will give undefined behavior. In our case, it always returns block 1, which is indicated by the returned `result.number` being `0x1`. A more "correct" result might be `null` or an error, but the "fix" to this isn't worth the time & lift to triage.

We'd happily review a PR to our ethermint fork: https://github.com/Kava-Labs/ethermint

**Comment by ozgrakkurt** [comment]
> Hi,
> 
> 
> 
> Unfortunately we don't plan to look into this. Block zero does not exist so requesting it will give undefined behavior. In our case, it always returns block 1, which is indicated by the returned `result.number` being `0x1`. A more "correct" result might be `null` or an error, but the "fix" to this isn't worth the time & lift to triage.
> 
> 
> 
> We'd happily review a PR to our ethermint fork: https://github.com/Kava-Labs/ethermint

Thank you anyway 👍. We are just indexing starting from block 1 now so all good.
