### ISSUE TITLE
kava_2221-16000 cannot connect to persistent_peers

### ISSUE THREAD

**Issue by sylviahuang123** [Kava-Labs/kava#1810]
```
chain-id: kava_2221-16000
kava tag: v0.17.5
genesis-time: 2022-06-08T22:00 UTC. 
persistent_peers="c8543d201018ccf456f9b11f7a5a7991fd7a33bd@54.208.233.212:26656,e20480a04378c95361c6425ec2bdaac88ba76a00@65.21.76.44:26656"
genesis-hash: 8f2a663eee7fa27ad3209d346105881454f6678d7f539d44ec7de89fec883649
```
do you have valid persistent_peers or seeds? 
do you have testnet node guidance?

**Comment by pirtleshell** [comment]
Hello @sylviahuang123 ,

Testnet's current binary is `v0.25.0-alpha.1`
A member of the community, @Remi-IBS, posted their address book and a snapshot of testnet in our discord 4 days ago (thanks, remi!): https://snapshot.ibs.team/Kava-Testnet/

More responsive support for node operators is available in [discord](https://discord.gg/JJYnuCx). Hope that helps! Thanks!

**Comment by sylviahuang123** [comment]
thanks, so not the testnet repo as README mentioned https://github.com/Kava-Labs/kava-testnets?, how can I follow the upgrade in the future?

**Comment by pirtleshell** [comment]
The current testnet is "Testnet 16000". Links to the upgrade binaries are published every release to https://github.com/Kava-Labs/kava-testnets/tree/master/16000 and are referenced in upgrade proposals to testnet.

Upgrade announcements are made in the #testnet-announcements channel of discord.
