### ISSUE TITLE
`/staking/pool` seems not including vesting amounts

### ISSUE THREAD

**Issue by winslyn** [Kava-Labs/kava#262]
`/staking/pool` seems not including vesting amounts

#Request
```
curl localhost:1317/staking/pool
```

#Result
```
{
  "height": "1331",
  "result": {
    "not_bonded_tokens": "0",
    "bonded_tokens": "2133179869577"
  }
}
```

**Comment by karzak** [comment]
Thanks for reporting this. We looked into it and this is indeed correct behavior. Tokens that have never been bonded/unonded are not present in either the `not_bonded_tokens` pool nor the `bonded_tokens` pool. Additionally, inflation is set based on `bonded_tokens / total_supply`, not `bonded_tokens / not_bonded_tokens`, so this will not cause issues with inflation targeting.

**Comment by winslyn** [comment]
Thanks for looking into this.

This is what I get from Cosmos and Terra.

#Cosmos `/staking/pool`
```
{
  "not_bonded_tokens": "64516034709018",
  "bonded_tokens": "181443208869579"
}
```

#Terra `/staking/pool`
```
{
  "not_bonded_tokens": "778011968400312",
  "bonded_tokens": "218192535832113"
}
```

And `not_bonded_tokens` + `bonded_tokens` makes the total supply. I'm just curious why only Kava returns `not_bonded_tokens` as 0.

**Comment by liangping** [comment]
@karzak  better to fix it.  All explorers/wallets fetch bonded token data via this endpoint.

**Comment by karzak** [comment]
> Thanks for looking into this.
> 
> This is what I get from Cosmos and Terra.
> 
> #Cosmos `/staking/pool`
> 
> ```
> {
>   "not_bonded_tokens": "64516034709018",
>   "bonded_tokens": "181443208869579"
> }
> ```
> 
> #Terra `/staking/pool`
> 
> ```
> {
>   "not_bonded_tokens": "778011968400312",
>   "bonded_tokens": "218192535832113"
> }
> ```
> 
> And `not_bonded_tokens` + `bonded_tokens` makes the total supply. I'm just curious why only Kava returns `not_bonded_tokens` as 0.

This is a difference between version 0.34+ of `cosmos-sdk` and version `0.37+`, which is what `kava` uses. I have confirmed with the `cosmos-sdk` devs that the behavior is correct and it is no longer the case that `bonded_tokens` + `not_bonded_tokens` is the total supply. To get the total suppy, use `/supply/total`



> @karzak better to fix it. All explorers/wallets fetch bonded token data via this endpoint.

See above. Chains using `cosmos-sdk` v0.37 and higher don't initialize all tokens in the`not_bonded_pool`. The values of `/staking/pool` are correct.

**Comment by liangping** [comment]
thanks @karzak , we fixed this issue on our explorer yesterday.
