### ISSUE TITLE
small inconsistency on infos displayed on KVCLI

### ISSUE THREAD

**Issue by gbunea** [Kava-Labs/kava#264]
The infos provided while using kvlci have some small inconsistencies regarding the gas used and gas wanted. 

For example for a send tx if I used --gas=auto flag I receive the amount o estimated gas before broadcasing transaction but after the tx is sent the gas infos (gas wanted and gas used) are shown as 0 which is wrong (see attached picture)
<img width="1033" alt="Screenshot 2019-10-18 at 19 11 37" src="https://user-images.githubusercontent.com/15690364/67110588-c9f63b00-f1db-11e9-901a-e2ac706cbe12.png">

**Comment by karzak** [comment]
The default broadcast mode is `async`, which will return the transaction details before they are executed. To see the gas used, and weather or not the transaction succeeded, use:
`kvcli config broadcast-mode block`. 

See [here](https://cosmos.network/docs/cosmos-hub/gaiacli.html#tx-broadcasting) for more details.
