### ISSUE TITLE
Can not query data by tags from LCD/txs endpoint 

### ISSUE THREAD

**Issue by liangping** [Kava-Labs/kava#268]
https://look.ping.pub/kava-2/txs?action=delegate&destination-validator=kavavaloper1xftqdxvq0xkv2mu8c5y0jrsc578tak4m9u0s44&limit=50&page=1

where "action" and "destination-validator" are tags of txs

This Url is standard endpoint of LCD server. Better to fix it. it's very useful for wallet/explorer

**Comment by karzak** [comment]
the equivalent query is https://data.kava.io/txs?limit=50&page=1&message.action=delegate&delegate.validator=kavavaloper140g8fnnl46mlvfhygj3zvjqlku6x0fwu6lgey7
