### ISSUE TITLE
Token calculation error(gov deposit)

### ISSUE THREAD

**Issue by wlsaud619** [Kava-Labs/kava#269]
1) If amount is set to "kava" when depositing in governance, the calculation seems to be in error.
2) And in Msgs, kava seems to be added as ukava.

`kvcli tx gov deposit 1 100kava --from A --fees=5000ukava --chain-id=kava-2`
> txhash: 5C99AEF78EF7EE22F7319C58851C699FD186A0387CEF65B3245A7352674800EB

![image](https://user-images.githubusercontent.com/17901095/69033828-2f2f8d00-0a23-11ea-879e-c986a43c7d65.png)

**Comment by karzak** [comment]
`kava` is not a valid token amount, the cli only accepts `ukava`. While 1 KAVA = 1000000 ukava, there is no logic in the application that knows that.
