### ISSUE TITLE
how to reveal the swagger doc.

### ISSUE THREAD

**Issue by xinxuwangbitmax** [Kava-Labs/kava#278]
i am using the latest master branch to run kava node with https://github.com/Kava-Labs/launch/blob/master/kava-2/genesis.json genesis file.when I get http://127.0.0.1:26657, only few urls listed,,how can i get swagger doc to test the rpc?? THX

**Comment by karzak** [comment]
[rpc.kava.io](rpc.kava.io) is I believe what you are looking for.
