### ISSUE TITLE
zero values of sdk.Int & sdk.Dec cause panics in validate genesis

### ISSUE THREAD

**Issue by rhuairahrighairidh** [Kava-Labs/kava#297]
- `sdk.Int` and `sdk.Dec` contain pointers to`big.Int`s.
- So a newly initialized empty `sdk.Int` will contain a pointer with value `nil`.
- So when a method is called on it, there 's a panic due to trying to deference the nil pointer.
- So if you unmarshal a json genesis file that's missing some fields, those fields are set to the zero value. Then calling methods on the zero values panics for above reason.

Can be avoided by filling all `sdk.Dec` and `sdk.Int` json fields.

**Comment by karzak** [comment]
This refers to `nil` values, not zero values correct? Ie) `sdk.Int{}` is not safe, but `sdk.ZeroInt()` is fine?

**Comment by rhuairahrighairidh** [comment]
Yeah, the default/unitialized value of a sdk.Int contains a nil pointer, rather than being sdk.ZeroInt() as you might expect.
This is more a low priority cosmos sdk issue so I'll close it.
