### ISSUE TITLE
pricefeed querier does not handle market names containing slashes

### ISSUE THREAD

**Issue by rhuairahrighairidh** [Kava-Labs/kava#300]
If a market id is "BTC/USD",  the querier breaks.

It places the string into the query path, but because of the extra slash it parses the market id as "BTC".

These market ids can't be used in the rest server either for similar reason.
Maybe easiest to just not use slashes, and add some validation to prevent them being used.

**Comment by denalimarsh** [comment]
Closing this as we've de facto gone with a market format of "coinA:coinB" for the pricefeed.
