### ISSUE TITLE
Add MsgTransferCDP that transfers CDP ownership

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#324]
`type MsgTransferCDP struct {}` was unimplemented and marked with TODO, but will not be included in the CDP test net release. This issue was created to track the feature, replacing the orphaned TODO comment.

**Comment by karzak** [comment]
Consideration for implementing: 

1. Is it safe for this message to be signed by only the current CDP owner or does it need to be signed by both the current and the proposed owner.
2. Are there any conditions in which transfer of a CDP should not be allowed? Liquidation would happen in the begin block, so we don't need to explicitly check for that.
