### ISSUE TITLE
Increase in debt from fees does not automatically liquidate CDPs

### ISSUE THREAD

**Issue by rhuairahrighairidh** [Kava-Labs/kava#335]
Not high priority, posting issue just for reference.

Stability fees cause debt in CDPs to gradually increase at some interest rate. This will eventually put all CDPs over the liquidation ratio, and hence they should be liquidated. The current system does not automatically liquidate them in this case.

However, whenever a user interacts with a CDP, fees are updated and if the CDP is found to be over the limit it will be liquided on the next block. So you could trigger a liquidation by depositing a tiny deposit to a CDP.

**Comment by denalimarsh** [comment]
Worth noting that this issue does not impact user withdrawals. For withdrawals, fees are calculated and the `collateralization ratio > liquidation ratio` check occurs before the withdrawal is approved.

**Comment by karzak** [comment]
Closed via #449
