### ISSUE TITLE
Kava coin type not used for HD Path

### ISSUE THREAD

**Issue by JonnyKh** [Kava-Labs/kava#341]
According to bip44 coin type registry Kava registered id 459 
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

But current kava cli versions are using the ATOM id of 118 when generating the HD wallet path

**Comment by JonnyKh** [comment]
This is probably simple enough for me to submit a PR.
But the fix is going to break recovery for any wallet that was generated with cosmos coin type.
Do we need a way to handle this ?

**Comment by rhuairahrighairidh** [comment]
Thanks for bringing this up, we used to use the cosmos coin type but have since moved over to our own. There more details here: https://medium.com/kava-labs/key-generation-on-kava-mainnet-is-changing-b65c3d3e9001

We pushed a fix for the cli so now it defaults to the new coin type.
