### ISSUE TITLE
Discussion: emit events on module param update

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#342]
Emitting an event _AuctionParamsUpdated_ with _AttributeAuctionParams_ on param update will be useful for applications dependent on chain state. We can be more granular for important events, such as _PricefeedParamsMarketAdded_ or _CDPParamsCollateralRemoved_.

**Comment by rhuairahrighairidh** [comment]
A potential counter point: any param change will go through a 2 week voting process so will likely be well known about, and won't happen that frequently.
That said an event might be useful for coordinating the exact point params are updated.
