### ISSUE TITLE
Test rest-server's http endpoints

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#349]
Use Postman to test the internal testnet's rest-sever's http endpoints.

**Comment by denalimarsh** [comment]
There are some inconsistencies with the rest-server endpoints: 
[ ] pricefeed uses 'params', auction uses 'parameters', and cdp is 'cdp**s**/params'.

**Comment by denalimarsh** [comment]
1. Example successful request
**Req**: `http://34.66.103.188:1317/auth/accounts/kava1xq4cspcgl9thzmn6lkvd6dlx28wsr63zw4mlmf`
**Resp**: `{"height":"23618","result":{"type":"cosmos-sdk/Account","value":{"address":"kava1xq4cspcgl9thzmn6lkvd6dlx28wsr63zw4mlmf","coins":[{"denom":"btc","amount":"8000000000"},{"denom":"ukava","amount":"8950000000000"},{"denom":"usdx","amount":"9499000"},{"denom":"xrp","amount":"99890000000"}],"public_key":{"type":"tendermint/PubKeySecp256k1","value":"A2cO87rjbLAc46jYc+eHaHny5yCjNjsQ3QKOP6sBHn+c"},"account_number":"0","sequence":"13"}}}`

2. Get markets from pricefeed
**Req**: `curl -s http://34.66.103.188:1317/pricefeed/markets`
**Resp**: `{"error":"{\"codespace\":\"sdk\",\"code\":6,\"message\":\"no custom querier found for route markets\"}"}`

   
3. List auctions
**Req**:`curl -s http://34.66.103.188:1317/auction/auctions`
**Resp**: `{"error":"UnmarshalJSON expects a pointer"}`

   
4. Weird error message
**Req**: `curl -s http://34.66.103.188:1317/cdp/create`
**Resp**: `{"error":"{\"codespace\":\"sdk\",\"code\":6,\"message\":\"no custom querier found for route cdps\"}"}`

**Comment by rhuairahrighairidh** [comment]
On digging in there are quite issues
- some are missing the module name in the querier string `/custom/<mod name>/rawprices`
- the auction endpoints had typos - missed pointers, and a missed copy and paste
- the some of the pricefeed queriers don't pass back the expected params to the querier
- endpoint path naming inconsistencies as mentioned

**Comment by denalimarsh** [comment]
Fixed in https://github.com/Kava-Labs/kava/pull/359.
