### ISSUE TITLE
Update contrib REST examples to avoid using CLI

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/kava#374]
Currently, once the REST server is started, users can't query their account using the cli, and would have to track the account sequence manually. Update the guide to use the equivalent REST endpoint for querying accounts. See https://github.com/Kava-Labs/kava/pull/372#discussion_r381709594

**Comment by denalimarsh** [comment]
Closing this outdated. My testing shows that `kvcli q auth account $(kvcli keys show validator -a)` is successful on master latest while the rest server is running.
