### ISSUE TITLE
Consider merits of panic versus emitting error in begin blocker

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/kava#385]
Currently, we follow the general rule of thumb, "don't panic", for errors that may occur during the course of `BeginBlocker` functions, most notably in the cdp module, where we emit any errors as events. We should consider if this is the best approach before mainnet, and document it better if we continue using it.

**Comment by denalimarsh** [comment]
We've decided to always panic for errors that occur during the `BeginBlocker` or `EndBlocker` as seen in https://github.com/Kava-Labs/kava/blob/master/x/cdp/abci.go.
