### ISSUE TITLE
Should auctions enforce a min bid duration greater than zero

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/kava#426]
Setting `BidDuration` to zero (or any int < blockTime) means  that any bid on an auction will trigger it's close in the next block. If `BidDuration` is a governance param that can be changed by a committee member, I would favor enforcing something like `MinAllowedBidDuration = time.Second * 600` to prevent auctions from closing very rapidly in the case of a governance attack.

**Comment by rhuairahrighairidh** [comment]
This sounds sensible.
It could be implemented as a committee permission. The permission would only allow committee proposals that have `BidDuration` > some amount. But maybe we want the minimum hardcoded in the module.
