### ISSUE TITLE
Pricefeed simulator's price drifts towards 0

### ISSUE THREAD

**Issue by rhuairahrighairidh** [Kava-Labs/kava#430]
Looks like the price's generated by the pricefeed simultor operations gradually tends towards 0 even with different random seeds.
Not sure what's going on, maybe something to do with rounding?

There's a script to generate prices on branch `price-gen-script`. Running `go test ./x/pricefeed/simulator/operations` will write out a json file with prices (outputs to the `pricefeed/simulator/operations` folder).

**Comment by jmahess** [comment]
Fix: https://github.com/Kava-Labs/kava/pull/434
