### ISSUE TITLE
Should TestAppStateDeterminism run each seed 5 times?

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/kava#437]
In `app/sim_test.go (TestAppStateDeterminism)`, 3 seeds are tested, and each seed is run 5 times. 

```
numSeeds := 3
numTimesToRunPerSeed := 5
```

1. I can't think of a good reason to run an individual seed more than twice. 
2. Further, I think that `NumSeeds` should be 1, and if you want to really test determinism, you run the function many times (one seed per run), rather than having an arbitrary floor of three seeds per run. 

Thoughts?

**Comment by jmahess** [comment]
1) I don't think you are gaining much if anything by running one seed more that twice. It is hard to prove a negative - in this case prove that every run results in the same output and state with the same seed. Running twice should be a sufficient check.
2) I agree. It seems that 3 was just picked as an arbitrary number. Makes sense to just have it as 1 and rerun the function many times if you want to test different seeds.

**Comment by fedekunze** [comment]
Yeah this simulation takes too much time. I'd reduce it to 3 and 3 or 3 and 2

**Comment by rhuairahrighairidh** [comment]
I think running more than one seed per test gets higher code coverage. It should increase the likelihood of executing the line that produces undeterministic behaviour. Though running the sim for longer would probably be equivalent, and having the test pick a hardcoded number of seeds randomly sounds awkward to use.

We could remove that seed loop entirely? Then I believe the seed can be set with the -Seed flag, and whoever is running the test is free to pick the seed and numblocks as needed. They can run high numBlocks and/or lots of different seeds for a big test, or less for CI.
