### ISSUE TITLE
Unable to claim validator rewards with Ledger on version 0.3.5

### ISSUE THREAD

**Issue by shaimo** [Kava-Labs/kava#535]
Using the command:
```kvcli tx distribution withdraw-rewards kavavaloperXXX --from $(kvcli keys show KavaLedger -a) --commission --gas auto --gas-adjustment 1.6 --gas-prices 0.25ukava```

I'm getting the following error:
```ERROR: please open Cosmos app on the Ledger device - error: [APDU_CODE_INS_NOT_SUPPORTED] Instruction code not supported or invalid```

Tried it with both Nano S and Nano X (with most recent firmware and app version, and obviously with Cosmos app open).

Is there some other kvcli version where this would work?

**Comment by shaimo** [comment]
I tried this with version 0.4.1 and am getting the same error. Is there some other version that should be working?

**Comment by marbar3778** [comment]
@shaimo are you still running into this issue?

**Comment by shaimo** [comment]
@marbar3778 I think it was fixed after the last upgrade. Thanks
