### ISSUE TITLE
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 68073E1B206A071AC4C0134596C49A8B1E170F8416C445EA781EF1E04C57034B, got 993D4BA2007CC33C9F00EDC37691E813CAE2AC0F6A6C1683126862105E850707

### ISSUE THREAD

**Issue by 1971192997** [Kava-Labs/kava#615]
when the node  sync the data,got something wrong,as follows.
ERROR: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 68073E1B206A071AC4C0134596C49A8B1E170F8416C445EA781EF1E04C57034B, got 993D4BA2007CC33C9F00EDC37691E813CAE2AC0F6A6C1683126862105E850707
=================================================================
        this is the log detail 
I[2020-07-22|04:58:23.292] Committed state                              module=state height=381468 txs=0 appHash=7E318D8862B71AFF279ECDED774EC7E08F4019451930A89643467768D1E075E5
I[2020-07-22|04:58:25.037] Executed block                               module=state height=381469 validTxs=1 invalidTxs=0
I[2020-07-22|04:58:25.346] Committed state                              module=state height=381469 txs=1 appHash=68073E1B206A071AC4C0134596C49A8B1E170F8416C445EA781EF1E04C57034B

==================================================================
and  can U help slove this problem?

**Comment by 1971192997** [comment]
@fadeev @nddeluca @sunnya97 @lovincyrus

**Comment by fadeev** [comment]
Hm. I'm sure Kava folks have a better answer 😄 but this kind of error happens when a non-deterministic operation is used in handlers or keepers (for example, UUID generation). So, if a chain is restarted, it ends up in a different state, hence unexpected hash.

**Comment by 1971192997** [comment]
> Hm. I'm sure Kava folks have a better answer 😄 but this kind of error happens when a non-deterministic operation is used in handlers or keepers (for example, UUID generation). So, if a chain is restarted, it ends up in a different state, hence unexpected hash.

====================================

**Comment by denalimarsh** [comment]
Hello @1971192997, this issue can be solved by upgrading kvd to v0.9.1, clearing out the data with `unsafe-reset-all`, and catching up to the network. We recommend this downloadable [Kava chain snapshot](http://get.quicksync.io/old/kava-3-pruned.20200718.0505.tar.lz4) provided by chainlayer. A short guide for unpacking the snapshot can be found [here](https://docs.chainlayer.io/quicksync/kava-snapshot). Don't forget to update kvd before unpacking the snapshot.

A couple of others had similar issues, check out the validators channel of our [discord](https://discord.com/invite/kQzh3Uv) to stay up to date with Kava technical disccusions 👍

**Comment by 1971192997** [comment]
ok.got it done .    thanks so much.
