### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by wimel** [Kava-Labs/kava#656]
Using `v0.10.0`  in compilation give the following error:
```
go: downloading github.com/zondax/hid v0.9.0
go: downloading github.com/mimoo/StrobeGo v0.0.0-20181016162300-f8f6d4d2b643
go: downloading gopkg.in/ini.v1 v1.51.0
# github.com/zondax/hid
../go/pkg/mod/github.com/zondax/hid@v0.9.0/hid_enabled.go:22:11: fatal error: sys/poll.h: No such file or directory
  #include <sys/poll.h>
           ^~~~~~~~~~~~
compilation terminated.
Makefile:79: recipe for target 'install' failed
make: *** [install] Error 2
```

- Steps to reproduce:
```
git clone https://github.com/Kava-Labs/kava.git && cd kava/
git checkout v0.10.0
make install
```
- System information:
```
Ubuntu 18.04.5 LTS - bionic
Linux 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
go version go1.14.2 linux/amd64
```

_More info about this issue [here](https://github.com/karalabe/hid/issues/17) and [here](https://github.com/karalabe/hid/pull/18/commits/72f64017e1f91913f88110836870339572c0a11d)._

> Try to solve using the following versions of Go without being able to solve it:
>- go version go1.15.2 linux/amd64
>- go version go1.14.4 linux/amd64
>- go version go1.14.3 linux/amd64
>- go version go1.13.10 linux/amd64
>- go version go1.13 linux/amd64
>- go version go1.10.1 linux/amd64

**Comment by nddeluca** [comment]
Thanks for the detailed steps and information.  It looks like you might be missing build-essentials, or some of it's dependencies, or your C compiler is not configured correctly.

If you don't have build essentials installed, run `sudo apt-get install build-essential` and try `make install`again.

If you do have it installed already, then ubuntu 18.04, the 'sys/poll.h' should be found at `/usr/include/x86_64-linux-gnu/sys/poll.h` and `/usr/include/x86_64-linux-gnu` in the compilers search path.

Do you have this file?  And if so, is it in your search path?

If you are missing the file performing:
```
apt-get remove build-essential
apt autoremove
apt-get install build-essential
```
should restore it.

You can check the search path with `cc -xc -E -v -` and you should see something like

```
#include <...> search starts here:
 /usr/lib/gcc/x86_64-linux-gnu/7/include
 /usr/local/include
 /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
```

**Comment by wimel** [comment]
**Thank you very much!!** that was the mistake, I think it can be interesting to add those steps in the README, at least dependencies, clone the repository and build, something like:
```
### Install dependencies:
sudo apt install -y git make gcc build-essential

### If you can check the hash of genesis you need "jq":
sudo apt install -y jq

### Clone the repo and build:
git clone https://github.com/Kava-Labs/kava.git && cd kava/
git checkout v0.10.0
make install
```
