### ISSUE TITLE
pricefeed genesis panics on missing or expired posted_prices

### ISSUE THREAD

**Issue by rhuairahrighairidh** [Kava-Labs/kava#675]
pricefeed `InitGenesis` calls `SetPrice` on prices in the genesis file. This throws an error if prices are expired https://github.com/Kava-Labs/kava/blob/00f2068d1b2ed17cbae3510a83a6ec661fd01139/x/pricefeed/keeper/keeper.go#L56-L57

**Comment by karzak** [comment]
Fixed in #664
