### ISSUE TITLE
Sync too slow

### ISSUE THREAD

**Issue by wrayjohn157** [Kava-Labs/kava#736]
Hello, I am setting up a back up validator on a 2nd server using v.12.0 i have completed the bootstrap however, the chain pull is too slow to keep up. after boot strap -9K blocks from tip, 8 hours later -11K. What can be done, from discord, v.12.1 doesn't seem to fix this issues.

Please Advise.

**Comment by denalimarsh** [comment]
@wrayjohn157 hello, you can try using [QuickSync](https://kava.quicksync.io/), a community-managed tool that syncs from a daily or weekly chain snapshot.

**Comment by jingniao** [comment]
i setup node from quicksync
but block sync slower than block miner

**Comment by jingniao** [comment]
after update to 0.12.2,sync faster than 0.12.1
every block from 10s to 3-4s

**Comment by jingniao** [comment]
but cosmos sync is fast 3-4block every second

**Comment by pirtleshell** [comment]
hello all. slow syncing is a known problem that we are working on improving with every release. it has been found that increasing the pruning of a node can help. beyond starting from a recent snapshot, it's possible the process simply needs more resources that you have provided it.

let us know if there's something more we can help with and we can reopen this ticket.
